// frontend/src/components/main/Seeker.jsx
import { createEffect } from 'solid-js';
import { STATUS } from '../../constants/constants';
import { status } from '../../state/state';

const Seeker = () => {
  let ref;

  let prev;
  let curr = 0;

  createEffect(() => {
    // noinspection FallThroughInSwitchStatementJS
    switch (status()) {
      case STATUS.PLAYING:
        const play = time => {
          if (status() !== STATUS.PLAYING) return;
          if (prev) {
            curr += time - prev;
            ref.style.transform = `translateX(${ curr / 10 }px)`;
          }
          prev = time;
          requestAnimationFrame(play);
        };
        requestAnimationFrame(play);
        break;
      case STATUS.STOPPED:
        curr = 0;
        ref.style.transform = '';
      case STATUS.PAUSED:
        prev = null;
        break;
    }
  });

  return (
    <div ref={ ref } class="absolute left-[200px] border-x border-red-400 h-full cursor-grab z-[1]" />
  );
};

export default Seeker;

// src/lib/components/main/Seeker.svelte
<script lang="ts">
  import status from '$lib/stores/status';
  import { Status } from '$lib/util/definitions/status';
  import width from '$lib/stores/width';
  // @ts-ignore
  import { browser } from '$app/environment';
  import rate from '$lib/stores/rate';

  enum StatusTime {
    stop = -1,
    pause = -2
  }

  let animate: FrameRequestCallback;
  let elapsed: number = StatusTime.stop;
  let left = 0;
  let start: number | StatusTime = StatusTime.stop;

  // @ts-ignore
  !animate && browser && (
    animate = (time: DOMHighResTimeStamp): any => {
      if ($status !== Status.play) return;
      if (start === StatusTime.stop) start = time;
      else if (start === StatusTime.pause) start = time - elapsed;
      elapsed = time - start;
      left = $width / (1000 / $rate) * elapsed;
      requestAnimationFrame(animate);
    }
  );

  $: switch ($status) {
    case Status.pause:
      start = StatusTime.pause;
      break;
    case Status.play:
      requestAnimationFrame(animate);
      break;
    case Status.stop:
      left = 0;
      start = StatusTime.stop;
      break;
  }
</script>

<div class="absolute border-l border-l-red-500 h-full left-track-header z-[1]" style:transform="translateX({ left }px)" />
